impl WorkspaceApp {
    fn settings_general(&self, cx: &mut Context<Self>) -> Vec<AnyElement> {
        let settings = self.settings_store.settings();
        let data_dir = self
            .settings_store
            .path()
            .parent()
            .unwrap_or_else(|| self.settings_store.path())
            .display()
            .to_string();
        let cli_path = std::env::var_os("HOME")
            .map(|home| {
                std::path::PathBuf::from(home)
                    .join(".local")
                    .join("bin")
                    .join("oxt")
                    .display()
                    .to_string()
            })
            .unwrap_or_else(|| "~/.local/bin/oxt".to_string());

        vec![
            self.settings_card(
                "settings_view.general.language",
                "settings_view.general.language_hint",
                vec![self.language_select_row(settings.general.language, cx)],
            ),
            self.plain_settings_card(vec![
                self.card_title("settings_view.general.data_directory"),
                div()
                    .flex()
                    .flex_col()
                    .gap(px(4.0))
                    .child(
                        div()
                            .text_size(px(self.tokens.metrics.ui_text_sm))
                            .font_weight(gpui::FontWeight::MEDIUM)
                            .text_color(rgb(self.tokens.ui.text))
                            .child(self.i18n.t("settings_view.general.data_directory")),
                    )
                    .child(
                        div()
                            .text_size(px(self.tokens.metrics.ui_text_xs))
                            .text_color(rgb(self.tokens.ui.text_muted))
                            .child(self.i18n.t("settings_view.general.data_directory_hint")),
                    )
                    .into_any_element(),
                div()
                    .w_full()
                    .flex()
                    .flex_row()
                    .items_center()
                    .gap(px(16.0))
                    .child(
                        div()
                            .flex_1()
                            .min_w(px(0.0))
                            .text_size(px(self.tokens.metrics.ui_text_base))
                            .text_color(rgb(self.tokens.ui.text))
                            .font_family(settings_mono_font_family())
                            .truncate()
                            .child(data_dir),
                    )
                    .child(self.outline_button(
                        self.i18n.t("settings_view.general.change"),
                        ButtonSize::Sm,
                    ))
                    .into_any_element(),
                div()
                    .text_size(px(self.tokens.metrics.ui_text_xs))
                    .text_color(rgb(self.tokens.ui.warning))
                    .child(
                        self.i18n
                            .t("settings_view.general.data_directory_restart_notice"),
                    )
                    .into_any_element(),
            ]),
            self.plain_settings_card(vec![
                self.card_title("settings_view.general.cli_companion"),
                div()
                    .flex()
                    .flex_col()
                    .gap(px(4.0))
                    .child(
                        div()
                            .text_size(px(self.tokens.metrics.ui_text_sm))
                            .font_weight(gpui::FontWeight::MEDIUM)
                            .text_color(rgb(self.tokens.ui.text))
                            .child(self.i18n.t("settings_view.general.cli_tool")),
                    )
                    .child(
                        div()
                            .text_size(px(self.tokens.metrics.ui_text_xs))
                            .text_color(rgb(self.tokens.ui.text_muted))
                            .child(self.i18n.t("settings_view.general.cli_tool_hint")),
                    )
                    .into_any_element(),
                div()
                    .w_full()
                    .flex()
                    .flex_row()
                    .items_end()
                    .justify_between()
                    .gap(px(16.0))
                    .child(
                        div()
                            .flex_1()
                            .flex()
                            .flex_col()
                            .gap(px(10.0))
                            .min_w(px(0.0))
                            .child(
                                div()
                                    .flex()
                                    .flex_row()
                                    .items_center()
                                    .gap(px(10.0))
                                    .child(Self::render_lucide_icon(
                                        LucideIcon::Terminal,
                                        16.0,
                                        rgb(self.tokens.ui.text_muted),
                                    ))
                                    .child(
                                        div()
                                            .text_size(px(self.tokens.metrics.ui_text_sm))
                                            .font_family(settings_mono_font_family())
                                            .text_color(rgb(self.tokens.ui.text))
                                            .child("oxide"),
                                    )
                                    .child(self.text_badge(
                                        self.i18n.t("settings_view.general.cli_installed"),
                                        self.tokens.ui.success,
                                    )),
                            )
                            .child(
                                div()
                                    .w_full()
                                    .min_w(px(0.0))
                                    .text_size(px(self.tokens.metrics.ui_text_xs))
                                    .font_family(settings_mono_font_family())
                                    .text_color(rgb(self.tokens.ui.text_muted))
                                    .truncate()
                                    .child(cli_path),
                            ),
                    )
                    .child(self.outline_button(
                        self.i18n.t("settings_view.general.cli_uninstall"),
                        ButtonSize::Sm,
                    ))
                    .into_any_element(),
            ]),
        ]
    }

    fn settings_portable(&self) -> Vec<AnyElement> {
        vec![self.settings_card(
            "settings_view.general.portable_runtime",
            "settings_view.general.portable_runtime_disabled_hint",
            vec![
                self.value_row(
                    "settings_view.general.portable_root_dir",
                    "settings_view.general.portable_runtime_hint",
                    self.i18n
                        .t("settings_view.general.portable_instance_lock_unavailable"),
                ),
                self.value_row(
                    "settings_view.general.portable_activation",
                    "settings_view.general.portable_runtime_hint",
                    self.i18n.t("settings_view.general.portable_activation_disabled"),
                ),
                self.value_row(
                    "settings_view.general.portable_config_path",
                    "settings_view.general.portable_runtime_hint",
                    self.i18n
                        .t("settings_view.general.portable_instance_lock_unavailable"),
                ),
                self.value_row(
                    "settings_view.general.portable_biometric",
                    "settings_view.general.portable_runtime_hint",
                    self.i18n
                        .t("settings_view.general.portable_biometric_unsupported"),
                ),
                self.value_row(
                    "settings_view.general.portable_change_password",
                    "settings_view.general.portable_runtime_hint",
                    self.i18n.t("common.disabled"),
                ),
                self.value_row(
                    "settings_view.general.cli_tool",
                    "settings_view.general.cli_tool_hint",
                    self.i18n.t("settings_view.general.cli_not_installed"),
                ),
                self.value_row(
                    "settings_view.general.cli_install",
                    "settings_view.general.cli_reinstall_hint",
                    self.i18n.t("settings_view.general.cli_not_bundled"),
                ),
            ],
        )]
    }

    fn settings_terminal(&self, cx: &mut Context<Self>) -> Vec<AnyElement> {
        let settings = self.settings_store.settings();
        let mut rows = vec![self.terminal_page_switcher(cx)];

        match self.terminal_settings_page {
            TerminalSettingsPage::Display => {
                rows.push(self.settings_card(
                    "settings_view.terminal.font",
                    "settings_view.terminal.font_family_hint",
                    vec![
                        self.select_setting_row(
                            "settings_view.terminal.font_family",
                            "settings_view.terminal.font_family_hint",
                            SettingsSelect::TerminalFontFamily,
                            font_family_label(settings.terminal.font_family),
                            self.tokens.metrics.settings_select_width,
                            cx,
                        ),
                        self.terminal_preview(settings),
                        self.card_separator(),
                        self.font_size_row(settings, cx),
                        self.card_separator(),
                        self.decimal_row(
                            "settings_view.terminal.line_height",
                            "settings_view.terminal.line_height_hint",
                            SettingsInput::TerminalLineHeight,
                            compact_decimal(settings.terminal.line_height),
                            cx,
                        ),
                        self.card_separator(),
                        self.select_setting_row(
                            "settings_view.terminal.encoding",
                            "settings_view.terminal.encoding_hint",
                            SettingsSelect::TerminalEncoding,
                            terminal_encoding_label(settings.terminal.terminal_encoding),
                            self.tokens.metrics.settings_select_width,
                            cx,
                        ),
                        self.card_separator(),
                        self.select_setting_row(
                            "settings_view.terminal.adaptive_renderer",
                            "settings_view.terminal.adaptive_renderer_hint",
                            SettingsSelect::TerminalAdaptiveRenderer,
                            adaptive_renderer_label(
                                settings.terminal.adaptive_renderer,
                                &self.i18n,
                            ),
                            self.tokens.metrics.settings_select_width,
                            cx,
                        ),
                        self.checkbox_row(
                            "settings_view.terminal.show_fps_overlay",
                            "settings_view.terminal.show_fps_overlay_hint",
                            settings.terminal.show_fps_overlay,
                            set_show_fps_overlay,
                            cx,
                        ),
                    ],
                ));
                rows.push(self.settings_card(
                    "settings_view.terminal.cursor",
                    "settings_view.terminal.cursor_style_hint",
                    vec![
                        self.select_setting_row(
                            "settings_view.terminal.cursor_style",
                            "settings_view.terminal.cursor_style_hint",
                            SettingsSelect::TerminalCursorStyle,
                            cursor_style_label(settings.terminal.cursor_style, &self.i18n),
                            self.tokens.metrics.settings_select_narrow_width,
                            cx,
                        ),
                        self.card_separator(),
                        self.checkbox_row(
                            "settings_view.terminal.cursor_blink",
                            "settings_view.terminal.cursor_blink_hint",
                            settings.terminal.cursor_blink,
                            set_terminal_cursor_blink,
                            cx,
                        ),
                    ],
                ));
            }
            TerminalSettingsPage::Input => {
                rows.push(self.terminal_input_settings_card(settings, cx));
            }
            TerminalSettingsPage::CommandBar => {
                rows.push(self.settings_card(
                    "settings_view.terminal.command_bar",
                    "settings_view.terminal.command_bar_hint",
                    vec![
                    self.bool_row(
                        "settings_view.terminal.command_bar",
                        "settings_view.terminal.command_bar_hint",
                        settings.terminal.command_bar.enabled,
                        set_command_bar_enabled,
                        cx,
                    ),
                    self.card_separator(),
                    self.bool_row(
                        "settings_view.terminal.command_bar_legacy_toolbar",
                        "settings_view.terminal.command_bar_legacy_toolbar_hint",
                        settings.terminal.command_bar.show_legacy_toolbar,
                        set_command_bar_legacy_toolbar,
                        cx,
                    ),
                    self.card_separator(),
                    self.value_row(
                        "settings_view.terminal.command_bar_focus_handoff",
                        "settings_view.terminal.command_bar_focus_handoff_hint",
                        settings
                            .terminal
                            .command_bar
                            .focus_handoff_commands
                            .join("\n"),
                    ),
                    self.card_separator(),
                    self.bool_row(
                        "settings_view.terminal.quick_commands",
                        "settings_view.terminal.quick_commands_hint",
                        settings.terminal.command_bar.quick_commands_enabled,
                        set_quick_commands_enabled,
                        cx,
                    ),
                    self.card_separator(),
                    self.bool_row(
                        "settings_view.terminal.quick_commands_confirm",
                        "settings_view.terminal.quick_commands_confirm_hint",
                        settings
                            .terminal
                            .command_bar
                            .quick_commands_confirm_before_run,
                        set_quick_commands_confirm,
                        cx,
                    ),
                    self.card_separator(),
                    self.bool_row(
                        "settings_view.terminal.quick_commands_toast",
                        "settings_view.terminal.quick_commands_toast_hint",
                        settings.terminal.command_bar.quick_commands_show_toast,
                        set_quick_commands_toast,
                        cx,
                    ),
                ],
                ));
            }
            TerminalSettingsPage::History => {
                rows.push(self.settings_card(
                    "settings_view.terminal.command_marks",
                    "settings_view.terminal.command_marks_hint",
                    vec![
                        self.bool_row(
                            "settings_view.terminal.command_marks",
                            "settings_view.terminal.command_marks_hint",
                            settings.terminal.command_marks.enabled,
                            set_command_marks_enabled,
                            cx,
                        ),
                        self.card_separator(),
                        self.bool_row(
                            "settings_view.terminal.command_marks_hover_actions",
                            "settings_view.terminal.command_marks_hover_actions_hint",
                            settings.terminal.command_marks.show_hover_actions,
                            set_command_marks_hover_actions,
                            cx,
                        ),
                    ],
                ));
                rows.push(self.settings_card(
                    "settings_view.terminal.buffer",
                    "settings_view.terminal.scrollback_hint",
                    vec![
                        self.number_row(
                            "settings_view.terminal.scrollback",
                            "settings_view.terminal.scrollback_hint",
                            settings.terminal.scrollback,
                            500,
                            500,
                            20000,
                            set_terminal_scrollback,
                            cx,
                        ),
                        self.card_separator(),
                        self.number_row(
                            "settings_view.terminal.backend_buffer_lines",
                            "settings_view.terminal.backend_buffer_lines_hint",
                            settings.buffer.max_lines,
                            500,
                            5000,
                            12000,
                            set_buffer_max_lines,
                            cx,
                        ),
                    ],
                ));
            }
            TerminalSettingsPage::Transfer => {
                rows.push(self.settings_card(
                    "settings_view.terminal.in_band_transfer.title",
                    "settings_view.terminal.in_band_transfer.runtime_note",
                    vec![
                        self.bool_row(
                            "settings_view.terminal.in_band_transfer.enabled",
                            "settings_view.terminal.in_band_transfer.enabled_hint",
                            settings.terminal.in_band_transfer.enabled,
                            set_in_band_transfer_enabled,
                            cx,
                        ),
                        self.card_separator(),
                        self.bool_row(
                            "settings_view.terminal.in_band_transfer.allow_directory",
                            "settings_view.terminal.in_band_transfer.allow_directory_hint",
                            settings.terminal.in_band_transfer.allow_directory,
                            set_in_band_transfer_allow_directory,
                            cx,
                        ),
                        self.card_separator(),
                        self.number_row(
                            "settings_view.terminal.in_band_transfer.max_chunk_bytes",
                            "settings_view.terminal.in_band_transfer.max_chunk_bytes_hint",
                            settings.terminal.in_band_transfer.max_chunk_bytes,
                            262144,
                            1024,
                            16 * 1024 * 1024,
                            set_in_band_transfer_max_chunk_bytes,
                            cx,
                        ),
                        self.card_separator(),
                        self.number_row(
                            "settings_view.terminal.in_band_transfer.max_file_count",
                            "settings_view.terminal.in_band_transfer.max_file_count_hint",
                            settings.terminal.in_band_transfer.max_file_count,
                            1,
                            1,
                            10000,
                            set_in_band_transfer_max_file_count,
                            cx,
                        ),
                        self.card_separator(),
                        self.number_row(
                            "settings_view.terminal.in_band_transfer.max_total_bytes",
                            "settings_view.terminal.in_band_transfer.max_total_bytes_hint",
                            settings.terminal.in_band_transfer.max_total_bytes / (1024 * 1024),
                            512,
                            1,
                            1024 * 1024,
                            set_in_band_transfer_max_total_mb,
                            cx,
                        ),
                        self.card_separator(),
                        self.value_row(
                            "settings_view.terminal.in_band_transfer.title",
                            "settings_view.terminal.in_band_transfer.runtime_note",
                            self.i18n
                                .t("settings_view.terminal.in_band_transfer.runtime_note"),
                        ),
                    ],
                ));
            }
            TerminalSettingsPage::Highlight => {
                rows.push(self.highlight_rules_card(settings, cx));
            }
        }

        rows
    }
}
