#!/usr/bin/env python3
"""Import static assets from the installed Material Icon Theme; no extension code runs."""

import argparse
import hashlib
import json
import xml.etree.ElementTree as ET
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
VERSION = "5.38.1"
RESOURCES = ROOT / "crates/oxideterm-gpui-ui/resources/material-icons"
GENERATED = ROOT / "crates/oxideterm-gpui-ui/src/file_icons/generated.rs"


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("extension", type=Path, help="Unpacked material-icon-theme 5.38.1 extension")
    extension = parser.parse_args().extension.resolve()
    package = json.loads((extension / "package.json").read_text())
    if package["name"] != "material-icon-theme" or package["version"] != VERSION:
        raise ValueError(f"Expected material-icon-theme {VERSION}")
    manifest = (extension / "dist/material-icons.json").read_bytes()
    theme = json.loads(manifest)
    assets = {}
    original_hashes = {}
    ET.register_namespace("", "http://www.w3.org/2000/svg")
    for name, definition in sorted(theme["iconDefinitions"].items()):
        source = (extension / "dist" / definition["iconPath"]).resolve()
        if not source.is_relative_to(extension / "icons") or source.suffix != ".svg":
            raise ValueError(f"Unexpected icon resource: {name}")
        data = source.read_bytes()
        original_hashes[source.name] = hashlib.sha256(data).hexdigest()
        root = ET.fromstring(data)
        if "viewBox" not in root.attrib:
            raise ValueError(f"Missing SVG viewBox: {name}")
        # GPUI caches full-color SVGs as images at their intrinsic resolution.
        # A 64 px raster keeps 14–16 px list icons sharp on high-density displays.
        root.set("width", "64")
        root.set("height", "64")
        assets[name] = (source.name, ET.tostring(root, encoding="unicode") + "\n")

    def icon(name, light_name=None):
        dark = "material-icons/" + assets[name][0]
        light = "material-icons/" + assets[light_name or name][0]
        return f"FileIcon::new({json.dumps(dark)}, {json.dumps(light)})"

    output = ["// Generated by scripts/import_material_icons.py; see resources/material-icons/SOURCE.md.",
              "use super::FileIcon;",
              f"pub(super) const DEFAULT: FileIcon = {icon(theme['file'])};",
              f"pub(super) const FOLDER: FileIcon = {icon(theme['folder'])};",
              f"pub(super) const FOLDER_OPEN: FileIcon = {icon(theme['folderExpanded'])};"]
    for source_key, rust_name in [("fileNames", "NAMES"), ("fileExtensions", "EXTENSIONS")]:
        associations = {key.lower(): (key, value) for key, value in theme[source_key].items()}
        output.append(f"pub(super) const {rust_name}: &[(&str, FileIcon)] = &[")
        for key, (original, value) in sorted(associations.items()):
            light = theme.get("light", {}).get(source_key, {}).get(original)
            output.append(f"    ({json.dumps(key, ensure_ascii=False)}, {icon(value, light)}),")
        output.append("];")
    folders = {key.lower(): key for key in theme["folderNames"]}
    output.append("pub(super) const FOLDERS: &[(&str, FileIcon, FileIcon)] = &[")
    for key, original in sorted(folders.items()):
        closed = icon(theme["folderNames"][original], theme["light"].get("folderNames", {}).get(original))
        opened = icon(theme["folderNamesExpanded"][original], theme["light"].get("folderNamesExpanded", {}).get(original))
        output.append(f"    ({json.dumps(key, ensure_ascii=False)}, {closed}, {opened}),")
    output.append("];")
    output.append("pub(super) fn asset(path: &str) -> Option<&'static [u8]> {\n    match path {")
    filenames = sorted({filename for filename, _ in assets.values()})
    for filename in filenames:
        output.append(f'        "material-icons/{filename}" => Some(include_bytes!("../../resources/material-icons/{filename}")),')
    output.extend(["        _ => None,", "    }", "}"])
    RESOURCES.mkdir(parents=True, exist_ok=True)
    GENERATED.parent.mkdir(parents=True, exist_ok=True)
    for filename, data in assets.values():
        (RESOURCES / filename).write_text(data)
    GENERATED.write_text("\n".join(output) + "\n")
    (ROOT / "licenses/third-party/MATERIAL-ICON-THEME-LICENSE-MIT").write_bytes((extension / "LICENSE.txt").read_bytes())
    source_digest = hashlib.sha256(json.dumps(original_hashes, sort_keys=True).encode()).hexdigest()
    (RESOURCES / "SOURCE.md").write_text(
        f"# Material Icon Theme {VERSION}\n\n"
        "Source: https://github.com/material-extensions/vscode-material-icon-theme\n"
        "Extension: https://marketplace.visualstudio.com/items?itemName=PKief.material-icon-theme\n\n"
        "Imported from the unpacked 5.38.1 extension. SVG root width/height are set to 64 px for GPUI's cached "
        "full-color image renderer; original paths, colors and viewBox are retained. File and folder associations, "
        "expanded folders and light variants come from dist/material-icons.json. No extension code is bundled.\n\n"
        "MIT license: licenses/third-party/MATERIAL-ICON-THEME-LICENSE-MIT at the repository root, also shipped in release packages.\n\n"
        "Regenerate with python3 scripts/import_material_icons.py /path/to/unpacked-extension.\n\n"
        f"Manifest SHA-256: {hashlib.sha256(manifest).hexdigest()}\n"
        f"Source icon hash-map SHA-256: {source_digest}\n")
    print(f"Imported {len(filenames)} SVG icons, {len(theme['fileNames']) + len(theme['fileExtensions'])} file associations and {len(folders)} folder names.")


if __name__ == "__main__":
    main()
